dist: trusty
sudo: false

language: node_js
node_js:
  - "8.11.1"
  
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  # Use Chromium instead of Chrome.
  - export CHROME_BIN=chromium-browser
  - xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox

before_deploy:
  - npm run build
  - cd ./dist

deploy:
  provider: heroku
  app: test-ci-04042018
  api_key:
    secure: "m1AaiNQyY6vTQ3s65Fr5JoJ4TWrLFUv8gc3Cuj78hKcf2GuuZndTyb3Tf0hLOySZgeViwBOCxRf+wuSIPb+q1hT5DnNzbeR5iRfMlKVW/GjGqUs/TIX0iJDXTvi1Up9LW/+An1kA5QQgeu9t0zMnMAiIqlgVVtoUVOPTiCx0wj5R2YSf0oSuuviJE4mGMOF7qemoYXpnHPfJS2+wNfv05oT8xnoxvfl3xQk44pCxrCyXL/3fzGAaE23q4NhRqhNDqoC4wgVTpgBH/LM26Ve4zUzSdRPIki/kF7ns/oEFxGjLuPrtyBKLhSkw5y7M+Xmizf7xneVv6g0YVrMfYBy0d99Qa0dll1zsojypKqyilR7HnlibvzJ7/T/XCWosSPKw+66K23+OYC19f6Vadi1eW5OmD/SJOHNknP/KI5BbkJrujuotwGF4gxE9lDNvPs54tOd5lBFst1P2wyRsW7h3CqedPAdJsFDNwoaMwLUKN+j2kZ7g1UId6fogaIbOLNQzj1uewTS1V95HtivUAWyf3nN5TFHN8CdfKa8XeL+MOjrN9OiZh0FzZoHs1NedQBaxoGbRvqwekb2g0rYzJYdz8FLa4593gjNzy/b4/vIjZeoy2qrfKEHaR65Lq/AsFUImkqcNnSeHaRyPwoftXN7ZJdYVRtUAtTvT0+PBZ0nz9Rw="
  skip_cleanup: true